name: Job Scraper

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/30 10-23,0 * * *" # Run every 30 minutes
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      # GOOGLE_KEY_JSON: ${{ secrets.GOOGLE_KEY_JSON }}
      ICONS_ID: ${{ secrets.ICONS_ID }}
      # ICONS_API: ${{ secrets.ICONS_API }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Cache pip download cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-cache-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-cache-

      - name: Set up virtual environment
        run: |
          python -m venv .venv
          .venv/bin/pip install --upgrade pip
          .venv/bin/pip install -r requirements.txt

      - name: Run job scraper
        run: .venv/bin/python main.py

      - name: Generate README
        run: .venv/bin/python generate_readme.py

      - name: Commit and push updated storage.json, readme and icons.json
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add storage.json README.md icons.json
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update storage.json, readme and icons.json [bot]"
            git pull --rebase origin main
            git push
          fi

  retry:
    needs: run
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    env:
      GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      # GOOGLE_KEY_JSON: ${{ secrets.GOOGLE_KEY_JSON }}
      ICONS_ID: ${{ secrets.ICONS_ID }}
      # ICONS_API: ${{ secrets.ICONS_API }}

    steps:
      - name: Wait for 5 minutes before retrying
        run: sleep 300

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Cache pip download cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-cache-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-cache-

      - name: Set up virtual environment
        run: |
          python -m venv .venv
          .venv/bin/pip install --upgrade pip
          .venv/bin/pip install -r requirements.txt

      - name: Run job scraper (Retry)
        run: .venv/bin/python main.py

      - name: Generate README
        run: .venv/bin/python generate_readme.py

      - name: Commit and push updated storage.json, readme and icons.json
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add storage.json README.md icons.json
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update storage.json, readme and icons.json [bot]"
            git pull --rebase origin main
            git push
          fi
